/**
 * Created by Chris on 17/5/27.
 */
//设置呼入号码 为user－info 的 callNo
export const SET_LOGIN_ALL_API = 'SET_LOGIN_ALL_API';
//设置呼入号码 为user－info 的 callNo
export const SET_CALL_NO_API = 'SET_CALL_NO_API';

//设置personMM 为空
export const SET_PERSON_EMPTY_API = 'SET_PERSON_EMPTY_API';

//用integrationIdSearch 搜索
export const SET_INTEGRATION_NO_API = 'SET_INTEGRATION_NO_API';
//设置输入号码 为业务号码
export const SET_BUSINESS_NO_API = 'SET_BUSINESS_NO_API';
//设置输入号码 为宽带
export const SET_BROADBAND_ACCOUNT_NO = 'SET_BROADBAND_ACCOUNT_NO';
//设置身份证 userinfo
export const SET_ID_USER_NO = 'SET_ID_USER_NO';
//设id来查 老系统
export const SET_INTEGRATION_OLD_NO_API = 'SET_INTEGRATION_OLD_NO_API';
//设置输入号码 为固定号码
export const SET_TELEPHONE_NO_API = 'SET_TELEPHONE_NO_API';
//设置输入号码 为有线宽带号码
export const SET_WIRED_BROAD_BAND_NO_API = 'SET_WIRED_BROAD_BAND_NO_API';
//设置输入号码 为ITV号码
export const SET_ITV_NO_API = 'SET_ITV_NO_API';


//设置输入号码 为宽带
export const SET_BROADBAND_ACCOUNT_API = 'SET_BROADBAND_ACCOUNT_API';

//呼入电话基本信息查询
export const GET_PERSON_API = 'GET_PERSON_API';
export const GET_PERSON_SAVE_API = 'GET_PERSON_SAVE_API';

//语音功能需要的入参数修改setBusiPhoneInfo
export const SET_BUSI_PHONE_INFO = 'SET_BUSI_PHONE_INFO';

//呼入电话资产
export const GET_ASSET_LIST_API = 'GET_ASSET_LIST_API';
//设置资产列表 入残
export const SET_ASSET_LIST_CONTRACT_IN = 'SET_ASSET_LIST_CONTRACT_IN';
export const SET_ASSET_LIST_ACCOUNT_IN = 'SET_ASSET_LIST_ACCOUNT_IN';
export const SET_ASSET_LIST_ID_IN = 'SET_ASSET_LIST_ID_IN';
export const SET_ASSET_LIST_ID_SEARCH_IN = 'SET_ASSET_LIST_ID_SEARCH_IN';


//设置资产列表
export const SET_ASSET_LIST_IN = 'SET_ASSET_LIST_IN';

export const SET_ASSET_LIST_CONTRACT = 'SET_ASSET_LIST_CONTRACT';
export const SET_ASSET_LIST_ACCOUNT = 'SET_ASSET_LIST_ACCOUNT';
export const SET_ASSET_LIST_ID = 'SET_ASSET_LIST_ID';
export const SET_ASSET_LIST_SEARCH_ID = 'SET_ASSET_LIST_SEARCH_ID';
export const SET_ON_ASSET_LIST_SEARCH_ID = 'SET_ON_ASSET_LIST_SEARCH_ID';

//同合同同客户
export const SET_ASSET_LIST_TOGETHER_IN = 'SET_ASSET_LIST_TOGETHER_IN';
//同合同
export const SET_ASSET_LIST_AGREEMENT_IN = 'SET_ASSET_LIST_AGREEMENT_IN';
//同客户
export const SET_ASSET_LIST_CUSTOMER_IN = 'SET_ASSET_LIST_CUSTOMER_IN';
//身份证
export const SET_ASSET_LIST_IDENTITY_IN = 'SET_ASSET_LIST_IDENTITY_IN';

//销售品下拉列表 新增接口
export const GET_SAME_CONTRACT_ASSET = 'GET_SAME_CONTRACT_ASSET';
//首页实名认证
export const GET_NEW_REAL_NAME_API = 'GET_NEW_REAL_NAME_API';
//根据录音编号查询报表话务分类（业务号码，大中小类）
export const SET_REPORT_BY_RECORD = 'SET_REPORT_BY_RECORD';
export const GET_REPORT_BY_RECORD = 'GET_REPORT_BY_RECORD';

//实名认证
export const SET_REAL_NAME_API = 'SET_REAL_NAME_API';
export const GET_REAL_NAME_API = 'GET_REAL_NAME_API';

//设置工具箱
export const SET_TOOL_BAR = 'SET_TOOL_BAR';
//获取工具箱
export const GET_GRT_TOOLBOX_API = 'GET_GRT_TOOLBOX_API';
//储存工具箱
export const GET_SAVE_TOOLBOX_API = 'GET_SAVE_TOOLBOX_API';

//客户画像
export const GET_PERSON_HEAD_API = 'GET_PERSON_HEAD_API';
//客户个人信息
export const GET_ACCOUNT_BUNDLE_API = 'GET_ACCOUNT_BUNDLE_API';
//客户账户余额
export const GET_CUSTOMER_ASSET_API = 'GET_CUSTOMER_ASSET_API';

//预判
export const GET_INDEX_MARKETING_API = 'GET_INDEX_MARKETING_API';
//营销
export const GET_PRECISION_MARKETING_API = 'GET_PRECISION_MARKETING_API';
//本月套餐
export const GET_FREE_RESOURCE_API = 'GET_FREE_RESOURCE_API';
//销售品
export const GET_SALE_PRODUCT_API = 'GET_SALE_PRODUCT_API';
//子产品
export const GET_SUB_ASSET_API = 'GET_SUB_ASSET_API';
//宽带率入参 新街口
export const SET_BROAD_BAND_RATE_API = 'SET_BROAD_BAND_RATE_API';
//宽带率入参 新街口 PAGE
export const SET_BROAD_BAND_RATE_PAGE_API = 'SET_BROAD_BAND_RATE_PAGE_API';
//子产品属性入参设置
export const SET_SUB_ASSET_PROPERTY_API = 'SET_SUB_ASSET_PROPERTY_API';
//子产品属性入参设置
export const SET_SUB_ASSET_PROPERTY_ZHU_API = 'SET_SUB_ASSET_PROPERTY_ZHU_API';
//子产品属性入参设置
export const GET_SUB_ASSET_PROPERTY_ZHU_API = 'GET_SUB_ASSET_PROPERTY_ZHU_API';
//子产品属性
export const GET_SUB_ASSET_PROPERTY_API = 'GET_SUB_ASSET_PROPERTY_API';

//子产品属性查询Widget接口
export const SET_FAMILY_NETWORK_LIST = 'SET_FAMILY_NETWORK_LIST';
export const GET_FAMILY_NETWORK_LIST = 'GET_FAMILY_NETWORK_LIST';


//IVR关联信息 来电预判
export const GET_USER_OPERATE_TRACE_QUERY_API = 'GET_USER_OPERATE_TRACE_QUERY_APIS';
//上一通电话
export const GET_LAST_CALL_API = 'GET_LAST_CALL_API';

//上一桶绘画足迹
export const GET_LAST_CALL_DETAIL_API = 'GET_LAST_CALL_DETAIL_API';

//电话 当日的数据
export const GET_CALL_LIST_DAY_API = 'GET_CALL_LIST_DAY_API';
//余额
export const GET_BALANCE_DETAIL__API = 'GET_BALANCE_DETAIL__API';
//电话当月
export const GET_CALL_LIST_MOUTH_API = 'GET_CALL_LIST_MOUTH_API';
//电话详情
export const SET_CALL_DETAIL_API = 'SET_CALL_DETAIL_API';
export const GET_CALL_DETAIL_API = 'GET_CALL_DETAIL_API';
//提示信息条数
export const GET_STAFF_UNREAD_SUM_API = 'GET_STAFF_UNREAD_SUM_API';
//获取话务员统计信息
export const GET_STAFF_STAT_INFO = 'GET_STAFF_STAT_INFO';
//接触轨迹
export const GET_CHANNEL_CONTACT_API = 'GET_CHANNEL_CONTACT_API';
//一证五号
export const SET_PHONE_REL_API = 'SET_PHONE_REL_API';
export const GET_PHONE_REL_API = 'GET_PHONE_REL_API';

// export const GET_IVR_API = 'GET_IVR_API';
//IVR 未知接口
export const GET_TRANSFER_PARAMS_API = 'GET_TRANSFER_PARAMS_API';
export const GET_LOGIN_INFO_API = 'GET_LOGIN_INFO_API';
export const GET_REGION_QUEUE_API = 'GET_REGION_QUEUE_API';
export const GET_REGION_QUEUE_AREA_API = 'GET_REGION_QUEUE_AREA_API';
export const GET_REGION_QUEUE_SKILL_API = 'GET_REGION_QUEUE_SKILL_API';
export const GET_TRANSFER_REGION_API = 'GET_TRANSFER_REGION_API';
export const GET_READ_BUSY_AND_QUEUE_API = 'GET_READ_BUSY_AND_QUEUE_API';


//IVR 设置
export const SET_TRANSFE_RREGION_API = 'SET_TRANSFE_RREGION_API';
export const SET_TRANSFER_PARAMS_API = 'SET_TRANSFER_PARAMS_API';
export const SET_REGION_QUEUE_AREA_API = 'SET_REGION_QUEUE_AREA_API';
export const SET_READ_BUSY_AND_QUEUE_API = 'SET_READ_BUSY_AND_QUEUE_API';
export const SET_REGION_QUEUE_SKILL_API = 'SET_REGION_QUEUE_SKILL_API';
export const GET_READ_BUSY_QUEUE_API = 'GET_READ_BUSY_QUEUE_API';
export const SET_READ_BUSY_API = 'SET_READ_BUSY_API';

//录音
export const SET_INSERT_USER_SATISFACTION_API = 'SET_INSERT_USER_SATISFACTION_API';
export const GET_INSERT_USER_SATISFACTION_API = 'GET_INSERT_USER_SATISFACTION_API';
export const SET_INSERT_USER_SATISFACTION_API_SM = 'SET_INSERT_USER_SATISFACTION_API_SM';
export const SET_ADD_RECORD_API = 'SET_ADD_RECORD_API';
export const SET_ADD_RECORD_API_SM = 'SET_ADD_RECORD_API_SM';
export const GET_ADD_RECORD_API = 'GET_ADD_RECORD_API';
export const SET_UPDATE_RECORD_API = 'SET_UPDATE_RECORD_API';
export const SET_UPDATE_RECORD_API_SM = 'SET_UPDATE_RECORD_API_SM';
export const GET_UPDATE_RECORD_API = 'GET_UPDATE_RECORD_API';

//IVR 随入数据
export const GET_IVR_FOLLOW_API = 'GET_IVR_FOLLOW_API';

//
export const SET_DAY_WIDGET_EMPTY = 'SET_DAY_WIDGET_EMPTY ';
export const SET_MOUTH_WIDGET_EMPTY = 'SET_MOUTH_WIDGET_EMPTY ';


//clear widget
export const SET_CALLIN_WIDGET_EMPTY = 'SET_CALLIN_WIDGET_EMPTY ';
export const SET_WIDGET_EMPTY = 'SET_WIDGET_EMPTY ';
export const SET_TRANFE_WIDGET_EMPTY = 'SET_TRANFE_WIDGET_EMPTY ';

//localAsset
export const SET_LOCAL_ASSET_EMPTY = 'SET_LOCAL_ASSET_EMPTY ';
//记事本
export const SET_SAVE_NOTE_API = 'SET_SAVE_NOTE_API ';
export const SET_QUERY_NOTE_LIST_API = 'SET_QUERY_NOTE_LIST_API ';
export const GET_QUERY_NOTE_LIST_API = 'GET_QUERY_NOTE_LIST_API ';
export const SET_DELETE_NOTES_API = 'SET_DELETE_NOTES_API ';
export const SET_COMPLETENOTES_API = 'SET_COMPLETENOTES_API ';

//我要反馈
export const SET_FEEDBACK_API = 'SET_FEEDBACK_API';
export const GET_FEEDBACK_API = 'GET_FEEDBACK_API';

//查询异网用户宽带账号 电话呼入时候查询
export const SET_KD_ACCOUNT_BY_CALL_NUM = 'SET_KD_ACCOUNT_BY_CALL_NUM';
export const GET_KD_ACCOUNT_BY_CALL_NUM = 'GET_KD_ACCOUNT_BY_CALL_NUM';
export const SET_KD_ACCOUNT_BY_CALL_DATA_NUM = 'SET_KD_ACCOUNT_BY_CALL_DATA_NUM';


//    <=====================   余额分析模块接口   ========================>

//  是否欠费查询
export const SET_BALANCE_INFO_API = 'SET_BALANCE_INFO_API ';
export const GET_BALANCE_INFO_API = 'GET_BALANCE_INFO_API ';

//  信用额度透支查询
export const SET_BALANCE_CREDIT_API = 'SET_BALANCE_CREDIT_API ';
export const GET_BALANCE_CREDIT_API = 'GET_BALANCE_CREDIT_API ';

//查询余额明细
export const SET_BALANCE_DEATIL_API = 'SET_BALANCE_DEATIL_API ';
export const GET_BALANCE_DEATIL_API = 'GET_BALANCE_DEATIL_API ';
//套餐用户翼支付划拨记录查询
export const SET_EPAY_CHARGE_BILL_RECORD_API = 'SET_EPAY_CHARGE_BILL_RECORD_API ';
export const GET_EPAY_CHARGE_BILL_RECORD_API = 'GET_EPAY_CHARGE_BILL_RECORD_API ';
//套餐用户翼支付划拨记录查询
export const SET_EPAY_CHARGE_BILL_PROGRESS_API = 'SET_EPAY_CHARGE_BILL_PROGRESS_API ';
export const GET_EPAY_CHARGE_BILL_PROGRESS_API = 'GET_EPAY_CHARGE_BILL_PROGRESS_API ';
//欠费明细查询服务
export const SET_OWE_CHARGE_DETAIL_API = 'SET_OWE_CHARGE_DETAIL_API ';
export const GET_OWE_CHARGE_DETAIL_API = 'GET_OWE_CHARGE_DETAIL_API ';
//待生效金额
export const SET_QUERY_BOOK_SCHEME_INFO_API = 'SET_QUERY_BOOK_SCHEME_INFO_API ';
export const GET_QUERY_BOOK_SCHEME_INFO_API = 'GET_QUERY_BOOK_SCHEME_INFO_API ';
//短信警告信息查询
export const SET_QUERY_ALARM_INFO_API = 'SET_QUERY_ALARM_INFO_API ';
export const GET_QUERY_ALARM_INFO_API = 'GET_QUERY_ALARM_INFO_API ';
//账务诊断
export const SET_BALANCE_IAGNOSIS_API = 'SET_BALANCE_IAGNOSIS_API ';
export const GET_BALANCE_IAGNOSIS_API = 'GET_BALANCE_IAGNOSIS_API ';
//使用客户合同号查询充值缴费记录
export const SET_QUERY_RECHARGE_LIST_API = 'SET_QUERY_RECHARGE_LIST_API ';
export const GET_QUERY_RECHARGE_LIST_API = 'GET_QUERY_RECHARGE_LIST_API ';
//使用客户合同号查询停复机记录记录
export const SET_QUERY_CALL_LIMIT_LIST_API = 'SET_QUERY_CALL_LIMIT_LIST_API ';
export const GET_QUERY_CALL_LIMIT_LIST_API = 'GET_QUERY_CALL_LIMIT_LIST_API ';
//历史话费返还查询
export const SET_QUERY_BILL_RETURN_DETAIL_API = 'SET_QUERY_BILL_RETURN_DETAIL_API ';
export const GET_QUERY_BILL_RETURN_DETAIL_API = 'GET_QUERY_BILL_RETURN_DETAIL_API ';
//历史红包返还查询
export const SET_RED_EPAY_CHARGE_BILL_RECORD_API = 'SET_RED_EPAY_CHARGE_BILL_RECORD_API ';
export const GET_RED_EPAY_CHARGE_BILL_RECORD_API = 'GET_RED_EPAY_CHARGE_BILL_RECORD_API ';
//余额变动查询
export const SET_BALANCE_CHANGE_LIST_API = 'SET_BALANCE_CHANGE_LIST_API ';
export const GET_BALANCE_CHANGE_LIST_API = 'GET_BALANCE_CHANGE_LIST_API ';
//历史余额变动查询
export const SET_QUERY_BALANCE_LOG_TOTAL_API = 'SET_QUERY_BALANCE_LOG_TOTAL_API ';
export const GET_QUERY_BALANCE_LOG_TOTAL_API = 'GET_QUERY_BALANCE_LOG_TOTAL_API ';
//历史合同欠费查询
export const SET_QUERY_OWE_CHARGE_INFO_API = 'SET_QUERY_OWE_CHARGE_INFO_API ';
export const GET_QUERY_OWE_CHARGE_INFO_API = 'GET_QUERY_OWE_CHARGE_INFO_API ';
//获取同合同列表
export const GET_SMS_CONTENT_LIST = 'GET_SMS_CONTENT_LIST';
